name: Build Docs

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocs-material-extensions mkdocs-static-i18n mkdocs-minify-plugin mkdocs-git-revision-date-localized-plugin jinja2

      - name: Build docs
        run: mkdocs gh-deploy --force
